// src/components/Preview.jsx
import { useState } from 'react';

export default function Preview({ url }) {
  const [loaded, setLoaded] = useState(false);

  if (!url) {
    return (
      <div className="preview-empty">
        <div className="loading-spinner" />
        <p>Waiting for dev server...</p>
      </div>
    );
  }

  return (
    <div className="preview-container">
      {!loaded && (
        <div className="preview-loading">
          <div className="loading-spinner" />
        </div>
      )}
      <iframe
        src={url}
        className="preview-iframe"
        style={{ opacity: loaded ? 1 : 0 }}
        onLoad={() => setLoaded(true)}
        title="preview"
        sandbox="allow-scripts allow-same-origin"
      />
    </div>
  );
}

// src/components/Preview.vue
<script setup>
defineProps({
  serverUrl: String,
  status: String, // 'waiting' | 'starting' | 'ready' | 'error'
  statusMessage: String,
})
</script>

<template>
  <div class="preview-panel">
    <!-- Waiting / starting -->
    <div v-if="status === 'waiting' || status === 'starting'" class="preview-empty">
      <div class="loading-spinner" />
      <p>{{ statusMessage || 'Waiting for dev server...' }}</p>
    </div>

    <!-- Error -->
    <div v-else-if="status === 'error'" class="preview-empty">
      <p style="color: #f48771">{{ statusMessage || 'Dev server failed to start' }}</p>
    </div>

    <!-- Ready: show iframe -->
    <div v-else-if="status === 'ready' && serverUrl" class="preview-container">
      <iframe
        :src="serverUrl"
        class="preview-iframe"
        title="preview"
        sandbox="allow-scripts allow-same-origin allow-forms"
      />
    </div>

    <!-- Fallback -->
    <div v-else class="preview-empty">
      <p>Unable to load preview</p>
    </div>
  </div>
</template>
